---
title: "Analysis of moss change"
author: "Wouter Van Landuyt, Hans Van Calster"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE)

#library(RODBC)
library(ggplot2)
#library(nlme)
#library(mgcv)
#library(lme4)
library(MASS)
#library(splines)
#library(stats)
library(vegan)
library(readxl)
library(rprojroot)
library(DHARMa)
library(tidyverse)
library(janitor)
library(inborutils)
library(inbodb) #remotes::install_github("inbo/inbodb", build_vignettes = TRUE)
```

```{r}

con <- connect_inbo_dbase("D0021_00_userFlora")
mosdata <- get_florabank_taxon_ifbl_year(
  connection = con,
  starting_year = 1980, 
  ifbl_resolution = "4km-by-4km", 
  taxongroup = "Mossen", 
  collect = TRUE
)

korstmosdata <- get_florabank_taxon_ifbl_year(
  connection = con,
  starting_year = 1980, 
  ifbl_resolution = "4km-by-4km", 
  taxongroup = "Lichenen (korstmossen)", 
  collect = TRUE
)


ellenberg <- get_florabank_traits(
  connection = con, 
  trait_name = "Ellenb", 
  collect = TRUE)

substraat <- get_florabank_traits(con, 
                     trait_name = "Substraat klassen mossen", 
                     collect = TRUE)

taxa <- tbl(src = con, "tblTaxon")
rel_groep <- tbl(src = con, "relTaxonTaxonGroep")
taxongroep <- tbl(src = con, "tblTaxonGroep")

taxa <- taxa %>%
  inner_join(rel_groep %>%
               select(-ID),
             by = c("ID" = "TaxonID")) %>%
  inner_join(taxongroep %>%
               filter(Naam %in% c("Mossen",
                                  "Lichenen (korstmossen)")
                      ) %>%
               select(-Code),
             by =  c("TaxonGroepID" = "ID")
             ) %>%
  collect()

dbDisconnect(con)
rm(con)
```


```{r}
korstmosdata <- korstmosdata %>%
  inner_join(taxa %>%
               select(ID, taxongroep = Naam), 
             by = c("TaxonIDParent" = "ID"))

mosdata <- mosdata %>%
  inner_join(taxa %>%
               select(ID, taxongroep = Naam), 
             by = c("TaxonIDParent" = "ID"))

alle_data <- bind_rows(mosdata, korstmosdata)
```

```{r}
ellenberg <- ellenberg %>%
  inner_join(alle_data %>%
               distinct(TaxonIDParent, taxongroep),
             by = c("TaxonID" = "TaxonIDParent"))
```


```{r}
alle_data <- alle_data %>%
  clean_names()
ellenberg <- ellenberg %>%
  clean_names()
taxa <- taxa %>%
  clean_names()
```

```{r eval=!file.exists(find_root_file("data/taxa_gbif.csv", criterion = is_git_root))}
taxa_gbif <- taxa %>%
  select(id, code, naam_nederlands, naam_wetenschappelijk,
         taxn_vrs_key, taxongroep = naam) %>%
  gbif_species_name_match(name = "naam_wetenschappelijk")
write_tsv(x = taxa_gbif, 
          path = find_root_file("data/taxa_gbif.csv", criterion = is_git_root))
```

```{r eval=file.exists(find_root_file("data/taxa_gbif.csv", criterion = is_git_root))}
taxa_gbif <- read_tsv(file = find_root_file("data/taxa_gbif.csv", criterion = is_git_root))
```



```{r}
geobserveerde_taxa <- taxa_gbif %>%
  semi_join(alle_data %>%
               distinct(taxon_id_parent),
             by = c("id" = "taxon_id_parent"))
```

```{r}
alle_data <- alle_data %>%
  left_join(geobserveerde_taxa %>%
              select(id, phylum),
            by = c("taxon_id_parent" = "id"))
```


## Exploratory data analysis


- Anthocerotophyta = hornworth = hauwmossen
- Bryophyta = bryophytes = bladmossen
- Marchantiophyta = liverworths = levermossen

```{r}
alle_data %>%
  group_by(taxongroep, phylum) %>%
  summarize(n_obs = n(),
            n_soorten = n_distinct(taxon_id_parent),
            n_hokken = n_distinct(ifbl_4by4)) %>%
  kable()
```


```{r}
alle_data %>%
  count(ifbl_4by4, jaar, name = "number of species") %>%
  ggplot() + 
  geom_density(aes(x = `number of species`, 
                     colour = factor(jaar))) + 
  ylab("density of ifbl 4 km x 4 km squares")
```

```{r}
alle_data %>%
  ggplot() + 
  geom_bar(aes(x = jaar, fill = phylum))
```


```{r}
species_freqs <- alle_data %>%
  filter(phylum != "Basidiomycota", 
         phylum != "Anthocerotophyta",
         !is.na(phylum)) %>%
  group_by(taxongroep, phylum) %>%
  mutate(n = n()) %>%
  group_by(taxongroep, phylum, taxon_id_parent) %>%
  summarise(
    n_obs = n(),
    prop_n_obs = n_obs/n[1],
    n_jaren = n_distinct(jaar),
    n_hokken = n_distinct(ifbl_4by4))
```


```{r}
species_freqs %>%
  ggplot() +
  geom_histogram(aes(x = prop_n_obs)) + 
  ylab("number of species") +
  facet_wrap(~phylum, scales = "free", ncol = 2)
```



```{r}
species_freqs %>%
  ggplot() +
  geom_histogram(aes(x = n_obs)) + 
  ylab("number of species") +
  facet_wrap(~phylum, scales = "free", ncol = 2)
```


## Telfer methode 

<!--
Telfer methode op uurhok??
hoe is totaal aantal hokken bepaald?
hoe gevallen proportie 0 en 1 aangepakt?
waar is de analyse waarmee CIuurhok (= residuals van de Telfer analyse?) bepaald werd?
-->



```{r}
analyse_data <- alle_data %>%
  filter(jaar != max(jaar)) %>%
  filter(phylum %in% c("Bryophyta", "Marchantiophyta")) %>%
  mutate(periode = ifelse(between(jaar, 1980, 1999),
                          "1980-1999", 
                          "2000-2019"))
```

```{r}
analyse_data %>%
  count(ifbl_4by4, periode, name = "number of species") %>%
  ggplot() + 
  geom_density(aes(x = `number of species`, 
                     colour = periode)) + 
  ylab("density of ifbl 4 km x 4 km squares") +
  geom_vline(xintercept = 40)
```

Goed onderzocht = 40 of meer soorten in een uurhok per periode 

Uurhok moet in beide perioden goed onderzocht zijn.

```{r}
analyse_data_telfer <- analyse_data %>%
  distinct(ifbl_4by4, taxon_id_parent, periode, taxongroep, phylum) %>%
  mutate(value = 1) %>%
  pivot_wider(id_cols = c(ifbl_4by4, taxon_id_parent, taxongroep, phylum),
              names_from = periode, 
              values_from = value, 
              values_fill = list(value = 0)) %>%
  group_by(ifbl_4by4) %>%
  filter(sum(`2000-2019`) >= 40,
         sum(`1980-1999`) >= 40) %>%
  ungroup() %>%
  pivot_longer(cols = c(`2000-2019`, `1980-1999`), 
               names_to = "periode", 
               values_to = "values") %>%
  filter(values == 1) %>%
  select(-values)

```

```{r}
analyse_data_telfer_agg <- analyse_data_telfer %>%
  group_by(periode) %>%
  mutate(n_hok_tot = n_distinct(ifbl_4by4)) %>%
  count(periode, taxongroep, phylum, taxon_id_parent, n_hok_tot, 
        name = "n_hok") %>%
  ungroup()
```


```{r}
analyse_data_telfer_agg <- analyse_data_telfer_agg %>%
  pivot_wider(id_cols = c(taxongroep, phylum, taxon_id_parent), 
              names_from = periode,
              values_from = c(n_hok, n_hok_tot), 
              values_fill = list(n_hok = 0)) %>%
  mutate(`n_hok_tot_2000-2019` = ifelse(is.na(`n_hok_tot_2000-2019`),
                                        max(`n_hok_tot_2000-2019`,
                                            na.rm = TRUE),
                                        `n_hok_tot_2000-2019`),
         `n_hok_tot_1980-1999` = ifelse(is.na(`n_hok_tot_1980-1999`),
                                        max(`n_hok_tot_1980-1999`,
                                            na.rm = TRUE),
                                        `n_hok_tot_1980-1999`),
         prop_baseline = (`n_hok_1980-1999` + 1) / `n_hok_tot_1980-1999`,
         prop_2000_2019 = (`n_hok_2000-2019` + 1) / `n_hok_tot_2000-2019`
         )
```


```{r}
# adding explanatory variables
ellenb_wide <- ellenberg %>%
  pivot_wider(id_cols = c(taxon_id), 
              names_from = kenmerk, 
              values_from = rekenwaarde) %>%
  select(taxon_id, 
         ell_l = `Ellenberg Licht`,
         ell_n = `Ellenberg Stikstof`,
         ell_f = `Ellenberg Vocht`,
         ell_r = `Ellenberg Reactiegetal`
         #, ell_t = `Ellenberg Temperatuur`
         )


analyse_data_telfer_agg <- analyse_data_telfer_agg %>%
  left_join(ellenb_wide, 
            by = c("taxon_id_parent" = "taxon_id")) %>%
  # warning! species can have more than one substrate -> Wouter already selected 
  # most important one, but this should be coded in the script?
  left_join(substraat %>% 
              clean_names() %>%
              select(taxon_id, substrate = omschrijving),
            by = c("taxon_id_parent" = "taxon_id")
            )
```

```{r}
analyse_data_telfer_agg <- analyse_data_telfer_agg %>%
  filter(complete.cases(analyse_data_telfer_agg)) %>%
  group_by(substrate) %>%
  filter(n() > 5)
```


```{r}
analyse_data_telfer_agg %>%
  ungroup() %>%
  select(starts_with("ell")) %>%
  pairs()
```


```{r}
alt_telfer <- glm(cbind(`n_hok_2000-2019` + 1,
                        `n_hok_tot_2000-2019` - `n_hok_2000-2019` - 1) ~ 
                    qlogis((`n_hok_1980-1999` + 1)/`n_hok_tot_1980-1999`)
                  + phylum 
                  + qlogis((`n_hok_1980-1999` + 1)/`n_hok_tot_1980-1999`):phylum 
                  + substrate
                  + ell_l
                  + ell_r
                  + ell_n
                  + ell_f
                  , 
    family = "binomial", 
    data = analyse_data_telfer_agg)

alt_telfer_opt <- MASS::stepAIC(alt_telfer)

```


```{r}
plotResiduals(alt_telfer_opt) #not good... proceeding anyway
plotResiduals(alt_telfer, 
              form = analyse_data_telfer_agg$phylum)
```

```{r}
nd <- expand.grid(
  `n_hok_1980-1999` = pretty(analyse_data_telfer_agg$`n_hok_1980-1999`,
                             n = 20),
  ell_r = unique(analyse_data_telfer_agg$ell_r),
  ell_l = unique(analyse_data_telfer_agg$ell_l),
  ell_f = unique(analyse_data_telfer_agg$ell_f),
  `n_hok_tot_1980-1999` = 232,
  phylum = unique(analyse_data_telfer_agg$phylum),
  substrate = unique(analyse_data_telfer_agg$substrate))
prd <- predict(alt_telfer_opt, 
               type = "link", 
               newdata = nd, 
               se = TRUE)
pred_alt_telfer <- nd %>%
  bind_cols(data.frame(
  link_est = prd$fit,
  link_se = prd$se)) %>%
  mutate(link_lwr = qnorm(p = 0.025, link_est, link_se),
         link_upr = qnorm(p = 0.975, link_est, link_se),
         response_est = plogis(link_est),
         response_lwr = plogis(link_lwr),
         response_upr = plogis(link_upr),
         prop_baseline = (`n_hok_1980-1999` + 1)/`n_hok_tot_1980-1999`)
```


```{r}
pred_alt_telfer %>%
  filter(ell_l == round(median(ell_l)),
         ell_f == round(median(ell_f)),
         ell_r == round(median(ell_r))) %>%
  ggplot(aes(x = prop_baseline, y = response_est)) + 
  #geom_point(data = analyse_data_telfer_agg,
  #           aes(y = prop_2000_2019,
  #               colour = substrate),
  #           alpha = 0.3) +
  geom_abline() +
  geom_ribbon(aes(ymin = response_lwr, 
                      ymax = response_upr,
                      fill = substrate), 
              alpha = 0.3) + 
  geom_line(aes(colour = substrate)) +
  facet_wrap(~phylum)
```

```{r}
pred_alt_telfer %>%
  filter(ell_l == round(median(ell_l)),
         ell_f == round(median(ell_f)),
         substrate == "Grond") %>%
  ggplot(aes(x = prop_baseline, y = response_est)) + 
  #geom_point(data = analyse_data_telfer_agg,
  #           aes(y = prop_2000_2019,
  #               colour = substrate),
  #           alpha = 0.3) +
  geom_abline() +
  geom_ribbon(aes(ymin = response_lwr, 
                      ymax = response_upr,
                      fill = factor(ell_r)), 
              alpha = 0.3) + 
  geom_line(aes(colour = factor(ell_r))) +
  facet_wrap(~phylum)
```


```{r}
pred_alt_telfer %>%
  filter(ell_l == round(median(ell_l)),
         ell_r == round(median(ell_r)),
         substrate == "Grond") %>%
  ggplot(aes(x = prop_baseline, y = response_est)) + 
  #geom_point(data = analyse_data_telfer_agg,
  #           aes(y = prop_2000_2019,
  #               colour = substrate),
  #           alpha = 0.3) +
  geom_abline() +
  geom_ribbon(aes(ymin = response_lwr, 
                      ymax = response_upr,
                      fill = factor(ell_f)), 
              alpha = 0.3) + 
  geom_line(aes(colour = factor(ell_f))) +
  facet_wrap(~phylum)
```


```{r}
pred_alt_telfer %>%
  filter(ell_f == round(median(ell_f)),
         ell_r == round(median(ell_r)),
         substrate == "Grond") %>%
  ggplot(aes(x = prop_baseline, y = response_est)) + 
  #geom_point(data = analyse_data_telfer_agg,
  #           aes(y = prop_2000_2019,
  #               colour = substrate),
  #           alpha = 0.3) +
  geom_abline() +
  geom_ribbon(aes(ymin = response_lwr, 
                      ymax = response_upr,
                      fill = factor(ell_l)), 
              alpha = 0.3) + 
  geom_line(aes(colour = factor(ell_l))) +
  facet_wrap(~phylum)

```



